version: '3.2'

services:
    api:
        ports:
            - 80:80
    database:
        ports:
            - 3306
    elasticsearch:
         ports:
             - 9200:9200
             - 9300:9300

