version: '3.2'

services:
  api:
        build: docker/api
        working_dir: /app
        environment:
            WEB_DOCUMENT_ROOT: /app/web
            WEB_DOCUMENT_INDEX: app.php
            PHP_DATE_TIMEZONE: "Europe/Paris"
            PHP_MAX_EXECUTION_TIME: 59
            PHP_DISPLAY_ERRORS: 1
            COMPOSER_MEMORY_LIMIT: -1
        env_file: .env
        depends_on:
            - database
            - elasticsearch
  database:
        image: percona:5.6
        volumes:
            - /docker/database:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wynd_api

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
      volumes:
          - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      environment:
          - "http.host=0.0.0.0"
          - "transport.host=127.0.0.1"
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  rabbitmq:
      image: rabbitmq:3-management
      environment:
          RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{queue,debug}]"